### ISSUE TITLE
Uncaught TypeError: win.external.msIsSiteMode is not a function

### ISSUE THREAD

**Issue by bitomule** [ttsvetko/HTML5-Desktop-Notifications#26]
I got this error under Chrome 43.0.2357 in OSX:

````
Uncaught TypeError: win.external.msIsSiteMode is not a function
````

It occurs in line 151:

````
} else if (win.external && (win.external.msIsSiteMode() !== undefined)) { /* keep last */
````

Any idea on what can be the issue?

**Comment by ttsvetko** [comment]
Fixed.

**Comment by sonmt23** [comment]
I still get this error in desktop-notify.js, please help!

`
function permissionLevel() {
        if (!isSupported) {return}
        if (win.Notification && win.Notification.permissionLevel) {
            return win.Notification.permissionLevel();
        } else if (win.webkitNotifications && win.webkitNotifications.checkPermission) {
            return PERMISSION[win.webkitNotifications.checkPermission()];
        } else if (win.external.msIsSiteMode()) {
            return PERMISSION_GRANTED
        }
    }

`
